CREATE TABLE push_deliveries (
  id BIGINT NOT NULL AUTO_INCREMENT,
  notification_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  binding_id VARCHAR(36) NOT NULL,
  token_version BIGINT NOT NULL,
  state VARCHAR(32) NOT NULL,
  attempt_id VARCHAR(36),
  attempt_count INT NOT NULL DEFAULT 0,
  expires_at DATETIME(6) NOT NULL,
  next_attempt_at DATETIME(6) NOT NULL,
  lease_until DATETIME(6),
  ticket_id VARCHAR(255),
  ticket_accepted_at DATETIME(6),
  receipt_next_at DATETIME(6),
  last_error_code VARCHAR(64),
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_push_delivery_binding UNIQUE (notification_id, device_id, binding_id),
  CONSTRAINT fk_push_delivery_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE,
  CONSTRAINT fk_push_delivery_device FOREIGN KEY (device_id) REFERENCES push_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_push_delivery_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX ix_push_delivery_due (state, next_attempt_at, id),
  INDEX ix_push_delivery_lease (state, lease_until, id),
  INDEX ix_push_delivery_receipt (state, receipt_next_at, id),
  INDEX ix_push_delivery_retention (created_at, id)
);
